import Head from 'next/head'
import Image from 'next/image'
import { Lista } from '@/components/lista'
import data from '../json/estilista/betterEstilista.json'
import { Main } from '@/components/main'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main data={data}/>
    </>
  )
}
